language: java

matrix:
    include:
        - os: linux
          sudo: false
          jdk: oraclejdk8
          addons:
              apt:
                  packages:
                      - oracle-java8-installer
                      - oracle-java8-set-default

script: ./gradlew check --info --stacktrace --console=plain

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
