name: "CI"

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/dists/gradle-6.6-milestone-1-bin/
          key: wrapper-6.6-milestone-1

      - name: Cache Gradle Dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/modules-2/
          key: dep-${{ hashFiles('gradle/**/*.*') }}-${{ hashFiles('**/*gradle.kts') }}

      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

      - name: Clean with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: clean

      - name: Build again with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

      - name: Before cache
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: rm -f ~/.gradle/caches/modules-2/*.lock ~/.gradle/caches/modules-2/gc.properties
